---
# Source: k8tz/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8tz
  namespace: k8tz-system
  labels:
    helm.sh/chart: k8tz-0.14.0
    app.kubernetes.io/name: k8tz
    app.kubernetes.io/instance: k8tz
    app.kubernetes.io/version: "0.14.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: k8tz/templates/admission-webhook.yaml
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLVENDQWhHZ0F3SUJBZ0lSQUs3Zmt5UlhUL1doUTlia3lXeGltZ1F3RFFZSktvWklodmNOQVFFTEJRQXcKSHpFZE1Cc0dBMVVFQXhNVWF6aDBlaTVyT0hSNkxYTjVjM1JsYlM1emRtTXdIaGNOTWpNeE1ERXlNakF4TnpRMwpXaGNOTXpjeE1ERXlNakF4TnpRM1dqQWZNUjB3R3dZRFZRUURFeFJyT0hSNkxtczRkSG90YzNsemRHVnRMbk4yCll6Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUwwbGZsbUZDSzJsa2tEdyt1b1QKejZjWFE4MktpZG5yL2w5VFFMcElFK2hZUUdMTEF6VW4vdGdXQTJlQzJ4QWRTZnBsSmg0dTlSVU80MEpOaWpvWAorWCtqdnRSMjd6TFJIQXdTS0VMWUJVWm5FNGdQcWF6QVVyUEZHbEhabnc0cTVORW90U21lYmtDRkNQZDByUzkzClV5enhuc1RxdjJmNnlFZENYNXNRRWd6TXdtR0FuaG9GSURyKzBlMzNqUGNiMjFQNjFtekZGdmNVQnJVb1AwRnQKMmc2SjkrNXoyRk4wRTZyeXo5UHI2a0V0Z2wvOXNRdXMrRDQycnM3V1RQVmUyRXBDRnFrWWpVeWxETkZEY21Zbwp2djZyN1FZK2N3dTEzSDZsbi9Zam4zazJPQVNMTzVHUTludWgyeGpkSktFdVRSVlppdEFKWDBud2tpMzJDc0cxCm5Wa0NBd0VBQWFOZ01GNHdEZ1lEVlIwUEFRSC9CQVFEQWdXZ01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUIKQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZEVRUVlNQmFDRkdzNGRIb3VhemgwZWkxegplWE4wWlcwdWMzWmpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFQckttQWpsVTByay9keHVBd09zQ1ZpZTdtClV6a2dSWmJ6VHZ2YUZ0cC9pTmhreHJkcmxWa1RUdXY4Y1gzcXo5R1RFWk4rM1kwTTVUVnZudWxaVll3VHdYaWIKVHh6cnM2OVVSVEEyKzg4Z3JxNG5sVGRCZFdrNUVJaTlRQ095VGg5QzhpM3A0clJqRUk4cXhZb2lhUjVnK0c5cgo5MFY1MGVULzFOY25IcXE2UjByLzZ3TVg4Y2daSHBYTFVMd0pySmlkOXEza1hLM1VxVnduSS9pcTQvemw5Q29aCnpsTU5RNlZpMDNQNFZ5RXhKWEc2NGNiUEQzNzcwcWlzeWFxYTlobE9ZV1BlRWQ3dDluRDgxUFZNQkJHbXlzTDcKZzQ0a3Y3Z1BhUkg1Y0k0VlpHWVJjSVJaamwyTmpqbUZ5bi8wK29VR3g3djRNdjRwcnV4VnJrbnRleEhHCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdlNWK1dZVUlyYVdTUVBENjZoUFBweGREellxSjJlditYMU5BdWtnVDZGaEFZc3NECk5TZisyQllEWjRMYkVCMUorbVVtSGk3MUZRN2pRazJLT2hmNWY2TysxSGJ2TXRFY0RCSW9RdGdGUm1jVGlBK3AKck1CU3M4VWFVZG1mRGlyazBTaTFLWjV1UUlVSTkzU3RMM2RUTFBHZXhPcS9aL3JJUjBKZm14QVNETXpDWVlDZQpHZ1VnT3Y3UjdmZU05eHZiVS9yV2JNVVc5eFFHdFNnL1FXM2FEb24zN25QWVUzUVRxdkxQMCt2cVFTMkNYLzJ4CkM2ejRQamF1enRaTTlWN1lTa0lXcVJpTlRLVU0wVU55WmlpKy9xdnRCajV6QzdYY2ZxV2Y5aU9mZVRZNEJJczcKa1pEMmU2SGJHTjBrb1M1TkZWbUswQWxmU2ZDU0xmWUt3YldkV1FJREFRQUJBb0lCQUZiMkRRQTFaTWNKVDVPaAo5NHAxTDB4Z0t1RXVKN0RVaW0valErZ2hTVjNTYlUrK2pLdjh4bk1zczhYOGFLRWhCaWtrSmdGTWo0dHQrOWc0CjlDcy9hSXRoaWxQK2xuempuU1NEbUpVYTRsbjYvQVRiUnFSUkMvVHcwdWY4eU43bm82bnlNRkNCTWFsaVFMd2MKblo4c0drYVlrK2x2RUM5TElwZDRrYUltSWxaVlp5YkRIbGRyeFQwZEZhRjVRRjRpbWtnQzBhaUdTV29iYytNRQpkVVA3ZzhyRjNrMjd3bkhLZmFHdmk4TlhpTEQ2aXFmS0RObXh3aE9VZDBZR3hGNnVvSnU1WWdyOVNBUGFBa0ZRCjRlMTNQeTBHN3gwZi9KamMrd2hxRkhGRG9ZUHhUN0VNL0xZYUh6K0FNVU4zQlpBTklPUEwvMVJmb0VPaXlrYVEKd21HRlV6RUNnWUVBMHR1QWtuTXdJTWl4c01OVlM1dloveVd5aEp0TzFFSnpySHh4SXNaSUtZd1pkQkU4VXNhWApGNFFsS3RxL2I0S0ZGaUhxYnE3dHlSWjkxNENFNmJZdk4zOGo0bWpOVHlyVG9vTzZnSlViRktWbElyU0tIQWNWCkxHZ0xRNTRnLzliZUVHemd2MjF5M0JCSlYwNDBuQ3ZOVTJyTmtvanZkNU12NW1BcE5teUQ5VFVDZ1lFQTVhUVQKRmE1Z0w1OEJkdHJVWnNNWk5lZC80UmlFTkJKYm9vdkZnbzBSVVVPcDZqMFdmSi9nMnd4Ni8yelk4YmkrRjJFWgpaWVdabTNpRVFDZGN3c0gxeUlUUitsWncyd0ZqUUk3ZzJEUzgrdEJ4bWdSL2tubmFrdFVZbHlrSXNSYkxraEtaCnhsMEpCNUhERVcwL2tnSDF5WXRPbStVaHFrOHpOOVBLSjFBb2dCVUNnWUVBbVdBdk10ZjAzelA5QkozaFVtRW8KZmc2MnZ2eVZwNUk2di9HNC9kbUxMaVdKY2tNRFJSYk5XcjYxcG1sOXJLZ2RGSTlSRG5mUjRWNnA1UExJTzVSWQozaDV1Uk1lRTZCdzMyMVBFZXJsNi9GYWVyVkx6enhWYjBuUlFGVHhWdHFOZDNrYkVhSm85WFZPL2RYRWVsYWJLCjhPMlVZUTJZV3J0R3NXV3JOTHBVZGkwQ2dZQVZkVnVETHlRMXp2bm9EVkxEdDM5bmxoWlJCbVYwS0RMLzRXZTMKWjA4eTlNdXY0NzF5TDg1bkthZGtydHNtMjBpSURyNjh5ZHNzdC9wRHRHbnFtUTFLaTM3RGtjaEI3c05EaVJaaApuYXY3RS9kSm1Sb0NxZmhPdURMd0RSbU8wcjU3QzlucXUwN1lzam8wS3ExQ0M0VFlMSGhRQVAxQVdONUVYVG9LCnFtYmVjUUtCZ0hpazdxdWU1a3BRVlRkcXVlb1lBa0tPOFgxUnNOdU1uSXo0QlpIT3pFWFVISUhqWElmYm9DZnAKR1NSM3FlUGdVZm1iUHJXYndkV0hJRnh4dGhvV0JQK05yV3p4SkIzS3pxZ2wxV1MvMVZiV1hPbWZGeDFhNEQ3aQpYeTRPaFJwL0FqMVl5eU9CNTZYUGlrbjc5cTdIQ1QycWsvWjdCYmNYT3U0ei9KZ3NIVzBPCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t
kind: Secret
metadata:
  namespace: k8tz-system
  creationTimestamp: null
  name: k8tz-tls
  labels:
    helm.sh/chart: k8tz-0.14.0
    app.kubernetes.io/name: k8tz
    app.kubernetes.io/instance: k8tz
    app.kubernetes.io/version: "0.14.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: k8tz/templates/rbac.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8tz-role
  labels:
    helm.sh/chart: k8tz-0.14.0
    app.kubernetes.io/name: k8tz
    app.kubernetes.io/instance: k8tz
    app.kubernetes.io/version: "0.14.0"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
# Source: k8tz/templates/rbac.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8tz-role-binding
  labels:
    helm.sh/chart: k8tz-0.14.0
    app.kubernetes.io/name: k8tz
    app.kubernetes.io/instance: k8tz
    app.kubernetes.io/version: "0.14.0"
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: k8tz
    namespace: k8tz-system
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: k8tz-role
---
# Source: k8tz/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: k8tz
  namespace: k8tz-system
  labels:
    helm.sh/chart: k8tz-0.14.0
    app.kubernetes.io/name: k8tz
    app.kubernetes.io/instance: k8tz
    app.kubernetes.io/version: "0.14.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: k8tz
    app.kubernetes.io/instance: k8tz
---
# Source: k8tz/templates/controller.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8tz
  namespace: k8tz-system
  labels:
    helm.sh/chart: k8tz-0.14.0
    app.kubernetes.io/name: k8tz
    app.kubernetes.io/instance: k8tz
    app.kubernetes.io/version: "0.14.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: k8tz
      app.kubernetes.io/instance: k8tz
  template:
    metadata:
      annotations:
        checksum/config: 244b7383794a3ece95021d4286a29d5ba1faaace4ddbfff6a450b32ee994c408
      labels:
        app.kubernetes.io/name: k8tz
        app.kubernetes.io/instance: k8tz
    spec:
      volumes:
      - name: tls
        secret:
          secretName: k8tz-tls
      serviceAccountName: k8tz
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: k8tz
          args:
          - "webhook"
          - "--timezone"
          - "UTC"
          - "--injection-strategy"
          - "initContainer"
          - "--inject=true"
          - "--bootstrap-image"
          - "quay.io/k8tz/k8tz:0.14.0"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          image: "quay.io/k8tz/k8tz:0.14.0"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: tls
              mountPath: /run/secrets/tls
              readOnly: true
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: https
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /health
              port: https
              scheme: HTTPS
          resources:
            {}
---
# Source: k8tz/templates/admission-webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: k8tz
  labels:
    helm.sh/chart: k8tz-0.14.0
    app.kubernetes.io/name: k8tz
    app.kubernetes.io/instance: k8tz
    app.kubernetes.io/version: "0.14.0"
    app.kubernetes.io/managed-by: Helm
webhooks:
  - name: admission-controller.k8tz.io
    namespaceSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
        - k8tz-system
        - kube-system
    sideEffects: None
    failurePolicy: Fail
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        name: k8tz
        namespace: k8tz-system
        path: "/"
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLVENDQWhHZ0F3SUJBZ0lSQUs3Zmt5UlhUL1doUTlia3lXeGltZ1F3RFFZSktvWklodmNOQVFFTEJRQXcKSHpFZE1Cc0dBMVVFQXhNVWF6aDBlaTVyT0hSNkxYTjVjM1JsYlM1emRtTXdIaGNOTWpNeE1ERXlNakF4TnpRMwpXaGNOTXpjeE1ERXlNakF4TnpRM1dqQWZNUjB3R3dZRFZRUURFeFJyT0hSNkxtczRkSG90YzNsemRHVnRMbk4yCll6Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUwwbGZsbUZDSzJsa2tEdyt1b1QKejZjWFE4MktpZG5yL2w5VFFMcElFK2hZUUdMTEF6VW4vdGdXQTJlQzJ4QWRTZnBsSmg0dTlSVU80MEpOaWpvWAorWCtqdnRSMjd6TFJIQXdTS0VMWUJVWm5FNGdQcWF6QVVyUEZHbEhabnc0cTVORW90U21lYmtDRkNQZDByUzkzClV5enhuc1RxdjJmNnlFZENYNXNRRWd6TXdtR0FuaG9GSURyKzBlMzNqUGNiMjFQNjFtekZGdmNVQnJVb1AwRnQKMmc2SjkrNXoyRk4wRTZyeXo5UHI2a0V0Z2wvOXNRdXMrRDQycnM3V1RQVmUyRXBDRnFrWWpVeWxETkZEY21Zbwp2djZyN1FZK2N3dTEzSDZsbi9Zam4zazJPQVNMTzVHUTludWgyeGpkSktFdVRSVlppdEFKWDBud2tpMzJDc0cxCm5Wa0NBd0VBQWFOZ01GNHdEZ1lEVlIwUEFRSC9CQVFEQWdXZ01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUIKQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZEVRUVlNQmFDRkdzNGRIb3VhemgwZWkxegplWE4wWlcwdWMzWmpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFQckttQWpsVTByay9keHVBd09zQ1ZpZTdtClV6a2dSWmJ6VHZ2YUZ0cC9pTmhreHJkcmxWa1RUdXY4Y1gzcXo5R1RFWk4rM1kwTTVUVnZudWxaVll3VHdYaWIKVHh6cnM2OVVSVEEyKzg4Z3JxNG5sVGRCZFdrNUVJaTlRQ095VGg5QzhpM3A0clJqRUk4cXhZb2lhUjVnK0c5cgo5MFY1MGVULzFOY25IcXE2UjByLzZ3TVg4Y2daSHBYTFVMd0pySmlkOXEza1hLM1VxVnduSS9pcTQvemw5Q29aCnpsTU5RNlZpMDNQNFZ5RXhKWEc2NGNiUEQzNzcwcWlzeWFxYTlobE9ZV1BlRWQ3dDluRDgxUFZNQkJHbXlzTDcKZzQ0a3Y3Z1BhUkg1Y0k0VlpHWVJjSVJaamwyTmpqbUZ5bi8wK29VR3g3djRNdjRwcnV4VnJrbnRleEhHCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
      - operations: [ "CREATE" ]
        apiGroups: ["batch"]
        apiVersions: ["v1"]
        resources: ["cronjobs"]
---
# Source: k8tz/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "k8tz-health-test"
  namespace: k8tz-system
  labels:
    helm.sh/chart: k8tz-0.14.0
    app.kubernetes.io/name: k8tz
    app.kubernetes.io/instance: k8tz
    app.kubernetes.io/version: "0.14.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: curl
      image: curlimages/curl:7.78.0
      args: ['--insecure', 'https://k8tz:443/health']
  restartPolicy: Never
